const PREFIX_CONFIRM_DIALOG = 'CONFIRM_DIALOG';
const PREFIX_CREATE_CONTAINER_DIALOG = 'CREATE_CONTAINER_DIALOG';
const PREFIX_TABS = 'TABS';
const PREFIX_IMAGES = 'IMAGES';
const PREFIX_CONTAINER_2_IMAGE = 'CREATE_IMAGE_FROM_CONTAINER_DIALOG';
const PREFIX_INPUT_DIALOG  = 'INPUT_DIALOG';
const PREFIX_CONTAINER  = 'CONTAINER';
const PREFIX_IMAGE_PULL_DIALOG = 'IMAGE_PULL_DIALOG';
const PREFIX_CONTAINER_LOGS_DIALOG = 'CONTAINER_LOGS_DIALOG';

export {
	PREFIX_CONTAINER_LOGS_DIALOG,
	PREFIX_IMAGE_PULL_DIALOG,
	PREFIX_CONFIRM_DIALOG,
	PREFIX_CREATE_CONTAINER_DIALOG,
	PREFIX_TABS,
	PREFIX_IMAGES,
	PREFIX_CONTAINER_2_IMAGE,
	PREFIX_INPUT_DIALOG,
	PREFIX_CONTAINER
};
